/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProjecoesRouteImport } from './routes/projecoes'
import { Route as ProjecaoRouteImport } from './routes/projecao'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LancamentosIndexRouteImport } from './routes/lancamentos.index'
import { Route as LancamentosNovoRouteImport } from './routes/lancamentos.novo'
import { Route as ConfiguracoesUsuariosRouteImport } from './routes/configuracoes.usuarios'
import { Route as ConfiguracoesPlanoDeContasRouteImport } from './routes/configuracoes.plano-de-contas'
import { Route as ConfiguracoesContasBancariasRouteImport } from './routes/configuracoes.contas-bancarias'
import { Route as AuthRedefinirSenhaRouteImport } from './routes/auth.redefinir-senha'
import { Route as ApiChatReportsRouteImport } from './routes/api/chat-reports'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicWebhooksPdvRestauranteRouteImport } from './routes/api/public/webhooks/pdv-restaurante'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjecoesRoute = ProjecoesRouteImport.update({
  id: '/projecoes',
  path: '/projecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjecaoRoute = ProjecaoRouteImport.update({
  id: '/projecao',
  path: '/projecao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosIndexRoute = LancamentosIndexRouteImport.update({
  id: '/lancamentos/',
  path: '/lancamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosNovoRoute = LancamentosNovoRouteImport.update({
  id: '/lancamentos/novo',
  path: '/lancamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesUsuariosRoute = ConfiguracoesUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesPlanoDeContasRoute =
  ConfiguracoesPlanoDeContasRouteImport.update({
    id: '/plano-de-contas',
    path: '/plano-de-contas',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesContasBancariasRoute =
  ConfiguracoesContasBancariasRouteImport.update({
    id: '/contas-bancarias',
    path: '/contas-bancarias',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const AuthRedefinirSenhaRoute = AuthRedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatReportsRoute = ApiChatReportsRouteImport.update({
  id: '/api/chat-reports',
  path: '/api/chat-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPdvRestauranteRoute =
  ApiPublicWebhooksPdvRestauranteRouteImport.update({
    id: '/api/public/webhooks/pdv-restaurante',
    path: '/api/public/webhooks/pdv-restaurante',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contas': typeof ContasRoute
  '/contatos': typeof ContatosRoute
  '/projecao': typeof ProjecaoRoute
  '/projecoes': typeof ProjecoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-reports': typeof ApiChatReportsRoute
  '/auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/configuracoes/contas-bancarias': typeof ConfiguracoesContasBancariasRoute
  '/configuracoes/plano-de-contas': typeof ConfiguracoesPlanoDeContasRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/lancamentos/novo': typeof LancamentosNovoRoute
  '/lancamentos/': typeof LancamentosIndexRoute
  '/api/public/webhooks/pdv-restaurante': typeof ApiPublicWebhooksPdvRestauranteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contas': typeof ContasRoute
  '/contatos': typeof ContatosRoute
  '/projecao': typeof ProjecaoRoute
  '/projecoes': typeof ProjecoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-reports': typeof ApiChatReportsRoute
  '/auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/configuracoes/contas-bancarias': typeof ConfiguracoesContasBancariasRoute
  '/configuracoes/plano-de-contas': typeof ConfiguracoesPlanoDeContasRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/lancamentos/novo': typeof LancamentosNovoRoute
  '/lancamentos': typeof LancamentosIndexRoute
  '/api/public/webhooks/pdv-restaurante': typeof ApiPublicWebhooksPdvRestauranteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contas': typeof ContasRoute
  '/contatos': typeof ContatosRoute
  '/projecao': typeof ProjecaoRoute
  '/projecoes': typeof ProjecoesRoute
  '/relatorios': typeof RelatoriosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-reports': typeof ApiChatReportsRoute
  '/auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/configuracoes/contas-bancarias': typeof ConfiguracoesContasBancariasRoute
  '/configuracoes/plano-de-contas': typeof ConfiguracoesPlanoDeContasRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/lancamentos/novo': typeof LancamentosNovoRoute
  '/lancamentos/': typeof LancamentosIndexRoute
  '/api/public/webhooks/pdv-restaurante': typeof ApiPublicWebhooksPdvRestauranteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas'
    | '/contatos'
    | '/projecao'
    | '/projecoes'
    | '/relatorios'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/chat-reports'
    | '/auth/redefinir-senha'
    | '/configuracoes/contas-bancarias'
    | '/configuracoes/plano-de-contas'
    | '/configuracoes/usuarios'
    | '/lancamentos/novo'
    | '/lancamentos/'
    | '/api/public/webhooks/pdv-restaurante'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas'
    | '/contatos'
    | '/projecao'
    | '/projecoes'
    | '/relatorios'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/chat-reports'
    | '/auth/redefinir-senha'
    | '/configuracoes/contas-bancarias'
    | '/configuracoes/plano-de-contas'
    | '/configuracoes/usuarios'
    | '/lancamentos/novo'
    | '/lancamentos'
    | '/api/public/webhooks/pdv-restaurante'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas'
    | '/contatos'
    | '/projecao'
    | '/projecoes'
    | '/relatorios'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/chat-reports'
    | '/auth/redefinir-senha'
    | '/configuracoes/contas-bancarias'
    | '/configuracoes/plano-de-contas'
    | '/configuracoes/usuarios'
    | '/lancamentos/novo'
    | '/lancamentos/'
    | '/api/public/webhooks/pdv-restaurante'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  ContasRoute: typeof ContasRoute
  ContatosRoute: typeof ContatosRoute
  ProjecaoRoute: typeof ProjecaoRoute
  ProjecoesRoute: typeof ProjecoesRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatReportsRoute: typeof ApiChatReportsRoute
  LancamentosNovoRoute: typeof LancamentosNovoRoute
  LancamentosIndexRoute: typeof LancamentosIndexRoute
  ApiPublicWebhooksPdvRestauranteRoute: typeof ApiPublicWebhooksPdvRestauranteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecoes': {
      id: '/projecoes'
      path: '/projecoes'
      fullPath: '/projecoes'
      preLoaderRoute: typeof ProjecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecao': {
      id: '/projecao'
      path: '/projecao'
      fullPath: '/projecao'
      preLoaderRoute: typeof ProjecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos/': {
      id: '/lancamentos/'
      path: '/lancamentos'
      fullPath: '/lancamentos/'
      preLoaderRoute: typeof LancamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos/novo': {
      id: '/lancamentos/novo'
      path: '/lancamentos/novo'
      fullPath: '/lancamentos/novo'
      preLoaderRoute: typeof LancamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/usuarios': {
      id: '/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof ConfiguracoesUsuariosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/plano-de-contas': {
      id: '/configuracoes/plano-de-contas'
      path: '/plano-de-contas'
      fullPath: '/configuracoes/plano-de-contas'
      preLoaderRoute: typeof ConfiguracoesPlanoDeContasRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/contas-bancarias': {
      id: '/configuracoes/contas-bancarias'
      path: '/contas-bancarias'
      fullPath: '/configuracoes/contas-bancarias'
      preLoaderRoute: typeof ConfiguracoesContasBancariasRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/auth/redefinir-senha': {
      id: '/auth/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/auth/redefinir-senha'
      preLoaderRoute: typeof AuthRedefinirSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat-reports': {
      id: '/api/chat-reports'
      path: '/api/chat-reports'
      fullPath: '/api/chat-reports'
      preLoaderRoute: typeof ApiChatReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/pdv-restaurante': {
      id: '/api/public/webhooks/pdv-restaurante'
      path: '/api/public/webhooks/pdv-restaurante'
      fullPath: '/api/public/webhooks/pdv-restaurante'
      preLoaderRoute: typeof ApiPublicWebhooksPdvRestauranteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthRedefinirSenhaRoute: typeof AuthRedefinirSenhaRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRedefinirSenhaRoute: AuthRedefinirSenhaRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ConfiguracoesRouteChildren {
  ConfiguracoesContasBancariasRoute: typeof ConfiguracoesContasBancariasRoute
  ConfiguracoesPlanoDeContasRoute: typeof ConfiguracoesPlanoDeContasRoute
  ConfiguracoesUsuariosRoute: typeof ConfiguracoesUsuariosRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesContasBancariasRoute: ConfiguracoesContasBancariasRoute,
  ConfiguracoesPlanoDeContasRoute: ConfiguracoesPlanoDeContasRoute,
  ConfiguracoesUsuariosRoute: ConfiguracoesUsuariosRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ConciliacaoRoute: ConciliacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  ContasRoute: ContasRoute,
  ContatosRoute: ContatosRoute,
  ProjecaoRoute: ProjecaoRoute,
  ProjecoesRoute: ProjecoesRoute,
  RelatoriosRoute: RelatoriosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatReportsRoute: ApiChatReportsRoute,
  LancamentosNovoRoute: LancamentosNovoRoute,
  LancamentosIndexRoute: LancamentosIndexRoute,
  ApiPublicWebhooksPdvRestauranteRoute: ApiPublicWebhooksPdvRestauranteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
